trigger:
  - none

parameters:
- name: env
  displayName: Environment
  type: string
  default: d
  values:
  - d

variables:
  - group: policy-${{parameters.env}}

pool:
  vmImage: windows-latest


steps:
- task: AzurePowerShell@5
  inputs:
    azureSubscription: $(azureSubscriptionConnection)
    ScriptType: 'InlineScript'
    azurePowerShellVersion: 'LatestVersion'
    Inline: |
      Install-Module Az.ResourceGraph
      Get-AzPolicyDefinition -Builtin|ConvertTo-Json
